### ISSUE TITLE
Convert a SchemaType back to JSON

### ISSUE THREAD

**Issue by amilkov1** [eclipsesource/play-json-schema-validator#114]
Is it possible to convert a `SchemaType` back to JSON after it has been extracted?

**Comment by edgarmueller** [comment]
You mean to a `JsValue`? Yes, that possible via Play's `Json.toJson`, e.g. in the tests we do:

```Scala
val stringConstraint = """{ "maxLength": 2 }"""
val schema: SchemaType = JsonSource.schemaFromString(stringConstraint).get
Json.toJson(schema) must beEqualTo(Json.obj("maxLength" -> 2))
```

Does this answer your question?

**Comment by amilkov1** [comment]
Oh wow yea that's exactly what I was going for. Thank you!
