### ISSUE TITLE
messages.txt can not be found

### ISSUE THREAD

**Issue by london-coder** [eclipsesource/play-json-schema-validator#140]
Hi,
I'm having a problem diagnosing an issue running the schema validator inside a Cucumber step. The code works reliably outside cucumber, either standalone or as a Scalatest. I have attached the stack trace and the code used inside the Cucumber test. I'm not sure whether anyone may have seen this issue in their experience with schema-validator.

Any help will be gratefully received.

[StackTrace.txt](https://github.com/eclipsesource/play-json-schema-validator/files/2495347/StackTrace.txt)

[CucumberSnippet.scala.txt](https://github.com/eclipsesource/play-json-schema-validator/files/2495355/CucumberSnippet.scala.txt)

Sorry about the file extension, github would not allow the upload of a .scala file.

**Comment by london-coder** [comment]
Having a look through the stack trace, and the project code. I would think there is some issue relating to the loading of "messages.txt" in the context of the Cucumber project. Is there some way to include / force the inclusion of messages.txt?

**Comment by london-coder** [comment]
As a check step, i copied the content of (validator project) messages.txt into another messages.txt that existed in the Cucumber project. This prevented the exception, but it is a "bodge". I would prefer to maintain the (validator project) messages.txt file in the cucumber project as a distinct resource bundle. I'm just trying to find a way to do this....

**Comment by london-coder** [comment]
I've found a solution to my problem. Please close the issue.

**Comment by edgarmueller** [comment]
Hi, no need to apologize. How did you solve the issue? I'm asking in case anybody else stumbles upon the problem.

**Comment by london-coder** [comment]
Hi Edgar,
The validator framework internally references (from SchemaRefResolver) messages.txt. In the cucumber test harness that applied the JSON validation against a micro service JSON response, also used a messages.txt that was loaded by the 'ResourceBundle'. The referenced key / value could not be found. 
My solution was, I copied (not sure if this is the 'optimal' way to do it), the validator framework messages.txt as messages_en.txt to the same 'resources' folder used by the Cucumber project. This cured the problem. Please feel free to suggest a better way to achieve the right result.

**Comment by edgarmueller** [comment]
Thanks for the update! From the top of my head I also can't think of any other solution (except for including validator's resources as well somehow), but your solution sounds like a solid workaround for the time being. The validator should probably provide defaults without relying on its resources, hence I'm leaving this issue open.

**Comment by leorodriguez** [comment]
@edgarmueller  It is actually falling back to any file starting with the string "messages", so the potential fix you mention would not be enough.

**Comment by edgarmueller** [comment]
Using any file that starts with `messages` in its name is the default behaviour of https://github.com/osinka/scala-i18n, which we use for internationalizing messages.  We'll likely not be able to change this behaviour soon as we are scare on resources. I have pushed a PR https://github.com/eclipsesource/play-json-schema-validator/pull/145 to provide default messages in case no message resource is found and I will also update the README to point this behaviour out. Once merged I'll close this issue. I hope that's fine, otherwise we are also accepting PRs of course.

**Comment by edgarmueller** [comment]
Part of 0.9.6-M1.
