### ISSUE TITLE
Release for scala 2.13

### ISSUE THREAD

**Issue by phb** [eclipsesource/play-json-schema-validator#143]
Now that scala 2.13 is out, would it be possible to make a new release for 2.13?

**Comment by edgarmueller** [comment]
Yes, sure, I'll try to make one this week.

**Comment by edgarmueller** [comment]
I had a quick look and it seems like we need to wait until the play dependencies are available for 2.13.

**Comment by phb** [comment]
Hi @edgarmueller, can you take a look again? As far as I can tell, they are available now.

**Comment by edgarmueller** [comment]
Yes, they are, thanks for letting me know! I'll try to update this week.

**Comment by edgarmueller** [comment]
I've released a new version with support for Scala 2.13 as 0.9.5.
