### ISSUE TITLE
How do i tag required keys ? 

### ISSUE THREAD

**Issue by sheshankkodam** [eclipsesource/play-json-schema-validator#22]
For example, if "title" is required key, how do i define it in the schema ? 

Here's is my code. Im expecting schema to fail to it passes. 

```Scala
val input3 = Json.toJson(
    Map(
      "id" -> Json.toJson(123),
      "body" -> Json.toJson("body")
    ))

val schema = Json.fromJson[SchemaType](
    Json.parse(
      """{
        |"properties": {
        |  "id":    { "type": "integer" },
        |  "title": { "type": "string", "minLength": 3 },
        |  "body":  { "type": "string" },
        |  "required": ["title"]
        |}
        |}""".stripMargin
    )
  ).get

println(Json.prettyPrint(input3))
val input3_result = SchemaValidator.validate(schema, input3)
println(f"input3 result: $input3_result")
```

RESULT:

> run
[info] Compiling 1 Scala source to C:\Users\sheshank.kodam\workspace\_SCALA\_IntelliJ\hello_json_validator\target\scala-2.11\classes...
[info] Running hello_json
{
  "id" : 123,
  "body" : "body"
}
input3 result: Success({"id":123,"body":"body"})
[success] Total time: 2 s, completed Jan 7, 2016 11:46:08 AM

**Comment by edgarmueller** [comment]
Hi, 
the `required` keyword needs to be put outside of the `properties`, which is not the case in your example. What you actually want is:

```Scala
val schema = Json.fromJson[SchemaType](
    Json.parse(
      """{
        |  "properties": {
        |    "id":    { "type": "integer" },
        |    "title": { "type": "string", "minLength": 3 },
        |    "body":  { "type": "string" }
        |  },
        |  "required": ["title"]
        |}""".stripMargin
    )
  ).get
```
[Here's](http://json-schema.org/examples.html) another example to illustrate the usage of `required`. Hope this helps.

**Comment by sheshankkodam** [comment]
Awesome ... worked .. Thanks
