### ISSUE TITLE
Cannot resolve symbol toJson

### ISSUE THREAD

**Issue by sheshankkodam** [eclipsesource/play-json-schema-validator#25]
Using the same code as shown in your readme but errors.toJson doesnt work

```scala
val result: VA[JsValue]= SchemaValidator.validate(schema, reqJson)
			result.fold(
				invalid = { errors => BadRequest(errors.toJson)},
				valid = { post => Ok(reqJson) }
			)

**Comment by edgarmueller** [comment]
You need to import `import com.eclipsesource.schema._` since the `toJson` method resides within the package object, but the docs do not mention the import. I'll update the docs accordingly. Thanks for pointing it out!

**Comment by edgarmueller** [comment]
I've updated the [Error Reporting](https://github.com/eclipsesource/play-json-schema-validator#error-reporting) section. Please let me know if the instructions are now clear enough. Thank you!
