### ISSUE TITLE
when supplied a valid (using fge) json schema draft v3, it incorrectly returns [ "Invalid JSON schema" ]

### ISSUE THREAD

**Issue by Mr-Nietzsche** [eclipsesource/play-json-schema-validator#29]
Ok, I see now that the repo states to be draft 4, but I got to the demo 1st; the problem is that the demo at https://ancient-atoll-3956.herokuapp.com/ should state that it only supports draft 4, b/c o.w when you compare it to other available validators, it appears to not work.
When the json schema has this line : 
"$schema":"http://json-schema.org/draft-03/schema",
at the root, it is valid according to draft v3.
Compare it to http://json-schema-validator.herokuapp.com/ (which uses https://github.com/fge/json-schema-validator)

**Comment by edgarmueller** [comment]
Thanks for pointing this out, I'll put a notice onto the validator page.

**Comment by edgarmueller** [comment]
Updated, on a side note: I've also updated the heroku URL to http://play-json-schema-validator.herokuapp.com/ which probably makes more sense. Thank you!
