### ISSUE TITLE
Scala 2.10 support?

### ISSUE THREAD

**Issue by c11z** [eclipsesource/play-json-schema-validator#30]
Looks like there is crossScalaSupport for 2.10 but the maven repo only has a _2.11 path.

**Comment by edgarmueller** [comment]
Thanks for pointing it out, I'll take care of this tomorrow.

**Comment by c11z** [comment]
Thanks! I ended up just downloading and adding it as a unmanaged jar, so take your time. But I like to keep everything in maven so thanks!

**Comment by edgarmueller** [comment]
Fixed with 0.6.4. Let me know if you need anything else. Thank!

**Comment by c11z** [comment]
Yes! I just made the switch in my build. This library is fantastic. Thanks
you!
