### ISSUE TITLE
Provide support for Play 2.5

### ISSUE THREAD

**Issue by kim-liedtke-rocket** [eclipsesource/play-json-schema-validator#37]
Hi,
We would really like to use this validator in our project.
Unfortunately the support ends with Play 2.4.
Would you be as kind as to fix this, please?

Best

**Comment by edgarmueller** [comment]
Hi,
yes, this should  be take care of. Unfortunately, I won't be able to do any work until the end of march.
@ottovw could you have a look at this?

**Comment by ottovw** [comment]
Hi @kim-liedtke-rocket 

we're waiting for jto/validation to update. At the same time we're evaluating whether we should cut that dependency and create a more standalone version of this library.

**Comment by edgarmueller** [comment]
After some consideration we've decided to cut jto/validation and released 0.7.0 today, which introduces breaking changes (mainly that we replaced `VA` with play-json's `JsResult`), but is compatible with Play 2.5. Let us know if this works for you and please re-open in case it does not.
Thanks!
