### ISSUE TITLE
validation error

### ISSUE THREAD

**Issue by mazorigal** [eclipsesource/play-json-schema-validator#39]
Hi, 

when using the method that validates schema and also converts to data model using predefined model Reads, in case the Reads trying to access non existing key, the validate method return an empty array of errors.

line 110:
https://github.com/eclipsesource/play-json-schema-validator/blob/master/src/main/scala/com/eclipsesource/schema/SchemaValidator.scala

**Comment by edgarmueller** [comment]
Hi, 
thanks for the report. I'll set up a test case for this.

**Comment by edgarmueller** [comment]
Read errors are exposed with 0.6.5. Unfortunately, currently not all the error information can be retrieved if Reads fail, i.e. `schemaPath` is unavailable. If there's anything else, please re-open.
