### ISSUE TITLE
uuid format

### ISSUE THREAD

**Issue by mazorigal** [eclipsesource/play-json-schema-validator#57]
Hi,

I am using "format": "uuid" for a string field.
and that is my example value:
6abd01c0-9236-4ba7-8cbd-3e866ad9385a

I have checked here:
http://www.uuid-validator.com/
and my uuid indeed valid one (version 4)

however when I am trying to validate the value, I am getting "Unknown format uuid"]

Thanks,

**Comment by edgarmueller** [comment]
Hi, the validator currently only supports the formats as described [here](https://spacetelescope.github.io/understanding-json-schema/reference/string.html), so there's no format for UUID currently, also see the [list of suggested formats](https://github.com/json-schema/json-schema/wiki/%22format%22-suggestions). But having such a format is defintely useful, so I'll be adding it, maybe together with an extension mechanism to also add custom formats.
Thanks for the input!

**Comment by edgarmueller** [comment]
I've updated the validator to 0.8.1 which supports custom formats and includes a built-in format `uuid`. For a usage example how to include custom formats, see [here](https://github.com/eclipsesource/play-json-schema-validator/blob/master/src/test/scala/com/eclipsesource/schema/FormatSpec.scala#L37). I'll update the docs accordingly the next days. If there are any questions, please go ahead.
