### ISSUE TITLE
Scala 2.12 version

### ISSUE THREAD

**Issue by oysterpack** [eclipsesource/play-json-schema-validator#83]
The key dependency that is blocking this project to cross-compile against scala 2.12 is play-json, which doesn't yet provide a scala 2.12 version.

**Comment by edgarmueller** [comment]
Thanks for the report!. I'll update once play-json is available for 2.12.

**Comment by olegstepura** [comment]
Hi! Any news?

**Comment by olegstepura** [comment]
Seems like `play-json` is still 2.11 =(

**Comment by edgarmueller** [comment]
Unfortunately yes. I check the versions regularly, but currently only milestones builds are available. If urgent, I could create a release with a milestone dependency.

**Comment by olegstepura** [comment]
Seems like there is version 2.12 already in maven

**Comment by edgarmueller** [comment]
I'll take that as a yes :) 
I'll try to release a Scala 2.12 version later today.

**Comment by edgarmueller** [comment]
Please update to 0.9.0 which will provide Scala 2.12 support (Scala 2.11 support is dropped with 0.9.x, I'll update the docs soon):
```
 "com.eclipsesource" %% "play-json-schema-validator" % "0.9.0"
```
Please re-open in case you encounter any problems.
