### ISSUE TITLE
Double.Min|MaxValue validation against integer property type

### ISSUE THREAD

**Issue by avkonst** [eclipsesource/play-json-schema-validator#94]
When I attempt to validate 
{
    "intprop" : 3.14
}
against the schema:
{
    "type" : "object",
    "properties" : {
      "intprop" : {
        "type" : "integer",
        "format" : "int32"
      }
}
I receive back:
[ {
      "schemaPath" : "#/properties/intprop",
      "errors" : { },
      "keyword" : "type",
      "msgs" : [ "Wrong type. Expected integer, was number." ],
      "value" : -3.14,
      "instancePath" : "/intprop"
} ]
It is correct.

However, when I validate the value:
{
    "intprop" : -1.7976931348623157E+308
}
against the same schema, there is no validation error trapped. I expected it to be be the same as for 3.14 value.

**Comment by edgarmueller** [comment]
Also fixed with 0.8.8.
